// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: position.proto

package position

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Format int32

const (
	Format_FORMAT_HUMAN  Format = 0
	Format_FORMAT_DEV_V1 Format = 1
)

// Enum value maps for Format.
var (
	Format_name = map[int32]string{
		0: "FORMAT_HUMAN",
		1: "FORMAT_DEV_V1",
	}
	Format_value = map[string]int32{
		"FORMAT_HUMAN":  0,
		"FORMAT_DEV_V1": 1,
	}
)

func (x Format) Enum() *Format {
	p := new(Format)
	*p = x
	return p
}

func (x Format) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Format) Descriptor() protoreflect.EnumDescriptor {
	return file_position_proto_enumTypes[0].Descriptor()
}

func (Format) Type() protoreflect.EnumType {
	return &file_position_proto_enumTypes[0]
}

func (x Format) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Format.Descriptor instead.
func (Format) EnumDescriptor() ([]byte, []int) {
	return file_position_proto_rawDescGZIP(), []int{0}
}

type Source int32

const (
	// This is live data from SMRT API
	Source_SOURCE_LIVE Source = 0
	// This is recorded data
	Source_SOURCE_RECORDED Source = 1
)

// Enum value maps for Source.
var (
	Source_name = map[int32]string{
		0: "SOURCE_LIVE",
		1: "SOURCE_RECORDED",
	}
	Source_value = map[string]int32{
		"SOURCE_LIVE":     0,
		"SOURCE_RECORDED": 1,
	}
)

func (x Source) Enum() *Source {
	p := new(Source)
	*p = x
	return p
}

func (x Source) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Source) Descriptor() protoreflect.EnumDescriptor {
	return file_position_proto_enumTypes[1].Descriptor()
}

func (Source) Type() protoreflect.EnumType {
	return &file_position_proto_enumTypes[1]
}

func (x Source) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Source.Descriptor instead.
func (Source) EnumDescriptor() ([]byte, []int) {
	return file_position_proto_rawDescGZIP(), []int{1}
}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Format Format            `protobuf:"varint,1,opt,name=format,proto3,enum=sg.lepak.mrtracker.position.Format" json:"format,omitempty"`
	Extra  map[string]string `protobuf:"bytes,2,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_position_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_position_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_position_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetFormat() Format {
	if x != nil {
		return x.Format
	}
	return Format_FORMAT_HUMAN
}

func (x *Request) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Format Format `protobuf:"varint,1,opt,name=format,proto3,enum=sg.lepak.mrtracker.position.Format" json:"format,omitempty"`
	// Time since Unix epoch in seconds
	LastUpdated uint64 `protobuf:"varint,2,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	// Data source
	Source Source `protobuf:"varint,3,opt,name=source,proto3,enum=sg.lepak.mrtracker.position.Source" json:"source,omitempty"`
	// Types that are assignable to DataOneof:
	//	*Response_HumanReadable
	//	*Response_DevV1
	DataOneof isResponse_DataOneof `protobuf_oneof:"data_oneof"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_position_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_position_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_position_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetFormat() Format {
	if x != nil {
		return x.Format
	}
	return Format_FORMAT_HUMAN
}

func (x *Response) GetLastUpdated() uint64 {
	if x != nil {
		return x.LastUpdated
	}
	return 0
}

func (x *Response) GetSource() Source {
	if x != nil {
		return x.Source
	}
	return Source_SOURCE_LIVE
}

func (m *Response) GetDataOneof() isResponse_DataOneof {
	if m != nil {
		return m.DataOneof
	}
	return nil
}

func (x *Response) GetHumanReadable() string {
	if x, ok := x.GetDataOneof().(*Response_HumanReadable); ok {
		return x.HumanReadable
	}
	return ""
}

func (x *Response) GetDevV1() *DevV1 {
	if x, ok := x.GetDataOneof().(*Response_DevV1); ok {
		return x.DevV1
	}
	return nil
}

type isResponse_DataOneof interface {
	isResponse_DataOneof()
}

type Response_HumanReadable struct {
	HumanReadable string `protobuf:"bytes,4,opt,name=human_readable,json=humanReadable,proto3,oneof"`
}

type Response_DevV1 struct {
	DevV1 *DevV1 `protobuf:"bytes,5,opt,name=dev_v1,json=devV1,proto3,oneof"`
}

func (*Response_HumanReadable) isResponse_DataOneof() {}

func (*Response_DevV1) isResponse_DataOneof() {}

type DevV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Data for SPI slave 0
	DataS0 []byte `protobuf:"bytes,1,opt,name=data_s0,json=dataS0,proto3" json:"data_s0,omitempty"`
	// Data for SPI slave 1
	DataS1 []byte `protobuf:"bytes,2,opt,name=data_s1,json=dataS1,proto3" json:"data_s1,omitempty"`
	// Data for SPI slave 2
	DataS2 []byte `protobuf:"bytes,3,opt,name=data_s2,json=dataS2,proto3" json:"data_s2,omitempty"`
}

func (x *DevV1) Reset() {
	*x = DevV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_position_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DevV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DevV1) ProtoMessage() {}

func (x *DevV1) ProtoReflect() protoreflect.Message {
	mi := &file_position_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DevV1.ProtoReflect.Descriptor instead.
func (*DevV1) Descriptor() ([]byte, []int) {
	return file_position_proto_rawDescGZIP(), []int{2}
}

func (x *DevV1) GetDataS0() []byte {
	if x != nil {
		return x.DataS0
	}
	return nil
}

func (x *DevV1) GetDataS1() []byte {
	if x != nil {
		return x.DataS1
	}
	return nil
}

func (x *DevV1) GetDataS2() []byte {
	if x != nil {
		return x.DataS2
	}
	return nil
}

var File_position_proto protoreflect.FileDescriptor

var file_position_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x1b, 0x73, 0x67, 0x2e, 0x6c, 0x65, 0x70, 0x61, 0x6b, 0x2e, 0x6d, 0x72, 0x74, 0x72, 0x61,
	0x63, 0x6b, 0x65, 0x72, 0x2e, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xc7, 0x01,
	0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3b, 0x0a, 0x06, 0x66, 0x6f, 0x72,
	0x6d, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x23, 0x2e, 0x73, 0x67, 0x2e, 0x6c,
	0x65, 0x70, 0x61, 0x6b, 0x2e, 0x6d, 0x72, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x52, 0x06,
	0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x45, 0x0a, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x73, 0x67, 0x2e, 0x6c, 0x65, 0x70, 0x61, 0x6b,
	0x2e, 0x6d, 0x72, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x45, 0x78, 0x74, 0x72,
	0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x1a, 0x38, 0x0a,
	0x0a, 0x45, 0x78, 0x74, 0x72, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x9b, 0x02, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x23, 0x2e, 0x73, 0x67, 0x2e, 0x6c, 0x65, 0x70, 0x61, 0x6b, 0x2e,
	0x6d, 0x72, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x52, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61,
	0x74, 0x12, 0x21, 0x0a, 0x0c, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x6c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x12, 0x3b, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x23, 0x2e, 0x73, 0x67, 0x2e, 0x6c, 0x65, 0x70, 0x61, 0x6b, 0x2e,
	0x6d, 0x72, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x12, 0x27, 0x0a, 0x0e, 0x68, 0x75, 0x6d, 0x61, 0x6e, 0x5f, 0x72, 0x65, 0x61, 0x64, 0x61,
	0x62, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0d, 0x68, 0x75, 0x6d,
	0x61, 0x6e, 0x52, 0x65, 0x61, 0x64, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x3b, 0x0a, 0x06, 0x64, 0x65,
	0x76, 0x5f, 0x76, 0x31, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x73, 0x67, 0x2e,
	0x6c, 0x65, 0x70, 0x61, 0x6b, 0x2e, 0x6d, 0x72, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x2e,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x44, 0x65, 0x76, 0x56, 0x31, 0x48, 0x00,
	0x52, 0x05, 0x64, 0x65, 0x76, 0x56, 0x31, 0x42, 0x0c, 0x0a, 0x0a, 0x64, 0x61, 0x74, 0x61, 0x5f,
	0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x22, 0x52, 0x0a, 0x05, 0x44, 0x65, 0x76, 0x56, 0x31, 0x12, 0x17,
	0x0a, 0x07, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x30, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x06, 0x64, 0x61, 0x74, 0x61, 0x53, 0x30, 0x12, 0x17, 0x0a, 0x07, 0x64, 0x61, 0x74, 0x61, 0x5f,
	0x73, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x64, 0x61, 0x74, 0x61, 0x53, 0x31,
	0x12, 0x17, 0x0a, 0x07, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x32, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x06, 0x64, 0x61, 0x74, 0x61, 0x53, 0x32, 0x2a, 0x2d, 0x0a, 0x06, 0x46, 0x6f, 0x72,
	0x6d, 0x61, 0x74, 0x12, 0x10, 0x0a, 0x0c, 0x46, 0x4f, 0x52, 0x4d, 0x41, 0x54, 0x5f, 0x48, 0x55,
	0x4d, 0x41, 0x4e, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x46, 0x4f, 0x52, 0x4d, 0x41, 0x54, 0x5f,
	0x44, 0x45, 0x56, 0x5f, 0x56, 0x31, 0x10, 0x01, 0x2a, 0x2e, 0x0a, 0x06, 0x53, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x5f, 0x4c, 0x49, 0x56,
	0x45, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x5f, 0x52, 0x45,
	0x43, 0x4f, 0x52, 0x44, 0x45, 0x44, 0x10, 0x01, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x6f, 0x2e, 0x6c,
	0x65, 0x70, 0x61, 0x6b, 0x2e, 0x73, 0x67, 0x2f, 0x6d, 0x72, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65,
	0x72, 0x2d, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_position_proto_rawDescOnce sync.Once
	file_position_proto_rawDescData = file_position_proto_rawDesc
)

func file_position_proto_rawDescGZIP() []byte {
	file_position_proto_rawDescOnce.Do(func() {
		file_position_proto_rawDescData = protoimpl.X.CompressGZIP(file_position_proto_rawDescData)
	})
	return file_position_proto_rawDescData
}

var file_position_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_position_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_position_proto_goTypes = []interface{}{
	(Format)(0),      // 0: sg.lepak.mrtracker.position.Format
	(Source)(0),      // 1: sg.lepak.mrtracker.position.Source
	(*Request)(nil),  // 2: sg.lepak.mrtracker.position.Request
	(*Response)(nil), // 3: sg.lepak.mrtracker.position.Response
	(*DevV1)(nil),    // 4: sg.lepak.mrtracker.position.DevV1
	nil,              // 5: sg.lepak.mrtracker.position.Request.ExtraEntry
}
var file_position_proto_depIdxs = []int32{
	0, // 0: sg.lepak.mrtracker.position.Request.format:type_name -> sg.lepak.mrtracker.position.Format
	5, // 1: sg.lepak.mrtracker.position.Request.extra:type_name -> sg.lepak.mrtracker.position.Request.ExtraEntry
	0, // 2: sg.lepak.mrtracker.position.Response.format:type_name -> sg.lepak.mrtracker.position.Format
	1, // 3: sg.lepak.mrtracker.position.Response.source:type_name -> sg.lepak.mrtracker.position.Source
	4, // 4: sg.lepak.mrtracker.position.Response.dev_v1:type_name -> sg.lepak.mrtracker.position.DevV1
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_position_proto_init() }
func file_position_proto_init() {
	if File_position_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_position_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_position_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_position_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DevV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_position_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*Response_HumanReadable)(nil),
		(*Response_DevV1)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_position_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_position_proto_goTypes,
		DependencyIndexes: file_position_proto_depIdxs,
		EnumInfos:         file_position_proto_enumTypes,
		MessageInfos:      file_position_proto_msgTypes,
	}.Build()
	File_position_proto = out.File
	file_position_proto_rawDesc = nil
	file_position_proto_goTypes = nil
	file_position_proto_depIdxs = nil
}
